# Generated by Django 3.0.5 on 2020-05-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Category',
            fields=[
                ('course_cate_id', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('course_cate', models.CharField(max_length=127)),
                ('course_cate_name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=127)),
                ('customer_mail', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=127)),
                ('course_overview', models.CharField(max_length=127)),
                ('course_price', models.IntegerField()),
                ('course_cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='learning.Course_Category')),
            ],
        ),
    ]
