# Generated by Django 3.0.5 on 2020-05-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_category',
            old_name='course_cate',
            new_name='course_cate_overview',
        ),
        migrations.AddField(
            model_name='course_category',
            name='course_image',
            field=models.CharField(default='NULL', max_length=127),
        ),
    ]
