# Generated by Django 3.0.6 on 2020-05-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20200521_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_category',
            name='course_image',
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='NULL', upload_to=''),
        ),
        migrations.AddField(
            model_name='course_category',
            name='course_category_image',
            field=models.ImageField(default='NULL', upload_to=''),
        ),
    ]
