# Generated by Django 2.2.7 on 2020-05-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
