# Generated by Django 2.2.7 on 2020-05-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_auto_20200523_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
