# Generated by Django 2.2.7 on 2020-05-23 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20200523_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 23, 11, 40, 46, 185175, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
