# Generated by Django 2.2.7 on 2020-05-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20200523_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('instructor_id', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('instructor_name', models.CharField(max_length=127)),
                ('instructor_overview', models.CharField(max_length=500)),
                ('instructor_image', models.ImageField(blank=True, default='NULL', upload_to='photo/instructor/')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, default='NULL', upload_to='photo/'),
        ),
    ]
