# Generated by Django 2.2.7 on 2020-05-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_coursereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='review_star',
            field=models.FloatField(),
        ),
    ]
