# Generated by Django 2.2.7 on 2020-05-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_auto_20200523_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.CharField(default='NULL', max_length=127),
        ),
        migrations.AddField(
            model_name='course',
            name='course_lecture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_long_overview',
            field=models.CharField(default='NULL', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='course_max_retake',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_percent_pass',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_quiz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_what_learn',
            field=models.CharField(default='NULL', max_length=500),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='review_star',
            field=models.IntegerField(),
        ),
    ]
