# Generated by Django 2.2.7 on 2020-05-24 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0014_auto_20200524_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_fn', models.CharField(max_length=200)),
                ('bill_ln', models.CharField(max_length=200)),
                ('bill_mail', models.CharField(max_length=200)),
                ('bill_address', models.CharField(max_length=200)),
                ('bill_country', models.CharField(max_length=200)),
                ('bill_city', models.CharField(max_length=200)),
                ('bill_zip', models.CharField(max_length=200)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.Course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
