# Generated by Django 2.2.7 on 2020-05-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
